# Generated by Django 5.2.8 on 2025-11-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_advisorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
