# Generated by Django 5.2.8 on 2025-11-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_chatmessage_advisor_remove_usersession_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorLog',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_chat_active',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
