# Generated by Django 5.2.8 on 2025-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
