# Generated by Django 5.2.8 on 2025-12-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_booking_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text="Mark this item as 'Coming Soon'"),
        ),
    ]
